### PR TITLE
Updated reports

### PR DESCRIPTION
**Pull request by joao-vicente**
Updated @context in all reports. Added a new rule report

### CODE REVIEW

**Review by jeeyyy — DISMISSED** [review]
Why are we diverging from using this context? - https://github.com/act-rules/act-rules-implementation-qualweb/pull/4/files#diff-1913a8aa59a056d00dc36f4ed3570579L2

**Comment by joao-vicente** [comment]
We needed to add a new attribute to the context. So in order to do that we copied it and added that new attribute. But before doing the merge, i need to fix the double "@context".

**Comment by jeeyyy** [comment]
Can we not extend the @context to act-rules?

**Comment by carlosapaduarte** [comment]
We were not sure if we could change the act-rules @context. We'll be happy to if there's nothing against it.

**Comment by joao-vicente** [comment]
@jkodu, where can i create a pull request to change the https://act-rules.github.io/earl-context.json?

**Comment by jeeyyy** [comment]
@joao-vicente @carlosapaduarte 

The file exists here - https://github.com/act-rules/act-rules-web/blob/master/build/earl-context.json

**Comment by jeeyyy** [comment]
Seems like all changes were directly pushed to master branch. Closing the issue.

**Review by jeeyyy — APPROVED** [review]

**Comment by jeeyyy** [comment]
@carlosapaduarte @joao-vicente. I misinterpreted in the email. I have reopened this PR.

Please merge this PR when you are ready. I have approved it. 
@carlosapaduarte you are the admin for this repo, so you should manage the PR's here. Thanks.

**Comment by carlosapaduarte** [comment]
@jkodu thanks! Will do!

**Pull request merged**
